PACKAGE_NAME="vc4-dkms"
PACKAGE_VERSION="1.0"
BUILD_EXCLUSIVE_KERNEL_MIN="6.1"
AUTOINSTALL="yes"

BUILT_MODULE_NAME[0]="vc4"
BUILT_MODULE_LOCATION[0]="src"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="make KERNEL_SOURCE_DIR='${kernel_source_dir}' KERNEL_VERSION=${kernelver} modules"

# gets the module source files and patches it before building
PRE_BUILD="prepare.sh"
